'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),Core=require('../noam-learning-core.js');
const catalog=[{id:'g9-t1-a'},{id:'g9-t1-b'}],iso='2026-09-08T10:00:00.000Z';
function storage(){const data=new Map();return{getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};}
function mock(){let rows=[],error=null,delay=null;return{setError:e=>error=e,setDelay:p=>delay=p,rows:()=>rows,from(){let op='get',body,filters=[],ignore=false,single=false;const q={select(){return q;},limit(){return q;},single(){single=true;return q;},eq(k,v){filters.push([k,v]);return q;},delete(){op='delete';return q;},upsert(v,o){op='upsert';body=v;ignore=o.ignoreDuplicates;return q;},async then(resolve,reject){try{if(delay)await delay;if(error)return resolve({error});const match=r=>filters.every(([k,v])=>r[k]===v);if(op==='delete'){rows=rows.filter(r=>!match(r));return resolve({data:[]});}if(op==='upsert'){for(const r of Array.isArray(body)?body:[body]){const i=rows.findIndex(x=>x.user_id===r.user_id&&x.worksheet_id===r.worksheet_id);if(i>=0&&ignore)continue;const value={...r,updated_at:iso};if(i>=0)rows[i]=value;else rows.push(value);}return resolve({data:single?rows.find(r=>r.user_id===body.user_id&&r.worksheet_id===body.worksheet_id):rows});}return resolve({data:rows.filter(match)});}catch(e){reject(e);}}};return q;}};}
test('guest progress persists per worksheet and level without authentication',async()=>{const s=storage(),e=Core.create({catalog,storage:s});await e.change('g9-t1-a','completed');assert.equal(e.snapshot().rows['g9-t1-a'].status,'completed');assert.equal(e.snapshot().rows['g9-t1-b'],undefined);const again=Core.create({catalog,storage:s});assert.equal(again.snapshot().rows['g9-t1-a'].status,'completed');await again.change('g9-t1-a',null);assert.deepEqual(again.snapshot().rows,{});});
test('invalid IDs, states, dates and malformed storage never create progress',async()=>{const s=storage();s.setItem(Core.storageKey,JSON.stringify({'g9-t1-a':{status:'constructor',updated_at:iso},'bad':{status:'completed',updated_at:iso},'g9-t1-b':{status:'started',updated_at:'invalid'}}));const e=Core.create({catalog,storage:s});assert.deepEqual(e.snapshot().rows,{});await assert.rejects(e.change('bad','completed'));await assert.rejects(e.change('g9-t1-a','passed'));});
test('storage failures reject rather than claim saved progress',async()=>{const e=Core.create({catalog,storage:{getItem(){throw Error();},setItem(){throw Error();}}});await assert.rejects(e.change('g9-t1-a','started'));assert.equal(e.snapshot().storageError,true);});
test('account state never leaks to guest storage or another account',async()=>{const c=mock(),s=storage(),e=Core.create({catalog,storage:s,client:c});assert.equal(e.snapshot().ready,false);await e.setUser({id:'alice'});await e.change('g9-t1-a','completed');assert.equal(s.getItem(Core.storageKey),null);await e.setUser({id:'bob'});assert.deepEqual(e.snapshot().rows,{});await e.setUser(null);assert.deepEqual(e.snapshot().rows,{});});
test('guest import is explicit and preserves existing account progress',async()=>{const c=mock(),s=storage(),e=Core.create({catalog,storage:s,client:c});await e.setUser(null);await e.change('g9-t1-a','completed');await e.change('g9-t1-b','review');await e.setUser({id:'alice'});assert.deepEqual(e.snapshot().rows,{});await e.change('g9-t1-a','started');await e.importGuest();assert.equal(e.snapshot().rows['g9-t1-a'].status,'started');assert.equal(e.snapshot().rows['g9-t1-b'].status,'review');assert.equal(e.snapshot().guestCount,2);});
test('failed cloud writes do not change visible status or fall back to guest',async()=>{const c=mock(),s=storage(),e=Core.create({catalog,storage:s,client:c});await e.setUser({id:'alice'});await e.change('g9-t1-a','started');c.setError(Error('offline'));await assert.rejects(e.change('g9-t1-a','completed'));assert.equal(e.snapshot().rows['g9-t1-a'].status,'started');assert.equal(s.getItem(Core.storageKey),null);assert.deepEqual(e.snapshot().pending,[]);});
test('a response arriving after signout cannot populate guest progress',async()=>{const c=mock(),s=storage(),e=Core.create({catalog,storage:s,client:c});await e.setUser({id:'alice'});let release;c.setDelay(new Promise(r=>release=r));const p=e.change('g9-t1-a','completed');await e.setUser(null);release();await p;assert.deepEqual(e.snapshot().rows,{});assert.equal(s.getItem(Core.storageKey),null);});
test('clearing an account leaves other accounts and guest storage unchanged',async()=>{const c=mock(),s=storage(),e=Core.create({catalog,storage:s,client:c});await e.setUser(null);await e.change('g9-t1-b','review');await e.setUser({id:'alice'});await e.change('g9-t1-a','started');await e.setUser({id:'bob'});await e.change('g9-t1-b','completed');await e.clear();await e.setUser({id:'alice'});assert.equal(e.snapshot().rows['g9-t1-a'].status,'started');await e.setUser(null);assert.equal(e.snapshot().rows['g9-t1-b'].status,'review');});
