// Builds a video package from an authored script.json and checks it against its source post.
// Authored files: packages/<postId>/<variant>/script.json, packages/<postId>/social.json,
// glossary.he.json. Everything else in a package is generated by bin/build.mjs.
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { VIDEO_ROOT, canonicalUrl, sha256, sourceBlocks, sourceHash } from './source.mjs';
import { checkFormula } from './mathcheck.mjs';
import { compareSpokenToDisplay } from './spokenmath.mjs';
import { isolateMath, removeIsolates, spokenTextProblems, stripNiqqud, unisolatedMath, vocalize, words, LRI, PDI } from './hebrew.mjs';

export const PACKAGES_DIR = join(VIDEO_ROOT, 'packages');
/**
 * Speaking-rate assumptions, both unmeasured. 14 chars/s is the figure the repo's
 * blog-audio pipeline uses for Hebrew TTS (blog-audio-pipeline/config.json on main);
 * 2.4 words/s (~144 wpm) is a common presenter pace. The estimate is their average,
 * reported with both ends. Only a rendered video gives a measured duration.
 */
export const RATE = { charsPerSec: 14, wordsPerSec: 2.4 };
export const CAPTION_DIFF_REASONS = {
  'numbers-in-words': 'מספרים נאמרים במילים; בכתובית הם בספרות, כמו בפוסט.',
  'numbers-and-operators-in-words': 'מספרים וסימני פעולה נאמרים במילים; בכתובית נשמר הביטוי המדויק, בבידוד LTR.',
  'letter-names-in-words': 'שמות אותיות (א׳, ב׳) נאמרים במילים: \"אלף\", \"בית\".',
};
const CUE_MAX = 42;

/** Strips up to three one-letter prefixes (ו ה ב ל כ מ ש) to group forms of one word. */
export const stem = (w) => w.replace(/^[\u05D5\u05D4\u05D1\u05DC\u05DB\u05DE\u05E9]{0,3}(?=[\u05D0-\u05EA]{3})/, '');

export function loadGlossary() {
  const g = JSON.parse(readFileSync(join(VIDEO_ROOT, 'glossary.he.json'), 'utf8'));
  const families = new Map();
  for (const e of g.entries) {
    const k = stem(e.token);
    const f = families.get(k) || { tokens: [], priority: false };
    f.tokens.push(e.token);
    f.priority ||= e.status === 'needs-listening-priority';
    families.set(k, f);
  }
  return { ...g, byToken: new Map(g.entries.map((e) => [e.token, e])), families, unpointedOkSet: new Set((g.unpointedOk || []).map((u) => u.token)) };
}

export function listPackages() {
  if (!existsSync(PACKAGES_DIR)) return [];
  const out = [];
  for (const postId of readdirSync(PACKAGES_DIR).sort()) {
    for (const variant of readdirSync(join(PACKAGES_DIR, postId)).sort()) {
      const p = join(PACKAGES_DIR, postId, variant, 'script.json');
      if (existsSync(p)) out.push({ postId, variant, dir: join(PACKAGES_DIR, postId, variant), scriptPath: p });
    }
  }
  return out;
}

export const readScript = (p) => JSON.parse(readFileSync(p, 'utf8'));
const capOf = (seg) => isolateMath(seg.caption ?? seg.spoken);
const spokenOf = (seg) => seg.spoken.normalize('NFC');

export function estimateSeconds(text) {
  const t = removeIsolates(text);
  const byChars = t.replace(/\s+/g, ' ').trim().length / RATE.charsPerSec;
  const byWords = words(t).length / RATE.wordsPerSec;
  return { byChars: +byChars.toFixed(1), byWords: +byWords.toFixed(1), mid: +((byChars + byWords) / 2).toFixed(1) };
}

/** Splits a caption into cues of at most CUE_MAX visible characters, never inside an LTR isolate. */
export function splitCues(caption) {
  const units = [];
  const re = new RegExp(`${LRI}[^${PDI}]*${PDI}\\S*|\\S+`, 'g');
  for (const m of caption.matchAll(re)) units.push(m[0]);
  const cues = [];
  let cur = '';
  const vis = (s) => removeIsolates(s).length;
  for (const u of units) {
    const next = cur ? `${cur} ${u}` : u;
    if (cur && (vis(next) > CUE_MAX || /[.?!:]$/.test(removeIsolates(cur)) && vis(cur) > CUE_MAX / 2)) { cues.push(cur); cur = u; } else cur = next;
  }
  if (cur) cues.push(cur);
  return cues;
}

/** The text a script contributes, rendered for every output file. */
export function render(script, post, glossary) {
  const segs = script.segments;
  const narration = segs.map((s) => vocalize(spokenOf(s), glossary.byToken, s.niqqudOverrides).normalize('NFC'));
  const captions = segs.map(capOf);
  const spoken = segs.map(spokenOf);
  const est = estimateSeconds(spoken.join(' '));
  // Cue timing is an estimate spread by word share; it is never a measured SRT.
  const total = est.mid;
  const totalWords = words(spoken.join(' ')).length;
  let t = 0;
  const cueSegments = segs.map((s, i) => {
    const segWords = words(spoken[i]).length;
    const segDur = (segWords / totalWords) * total;
    const cues = splitCues(captions[i]);
    const cueWords = cues.map((c) => Math.max(1, words(c).length));
    const sum = cueWords.reduce((a, b) => a + b, 0);
    let ct = t;
    const out = cues.map((c, k) => { const d = (cueWords[k] / sum) * segDur; const cue = { text: c, estStart: +ct.toFixed(1), estEnd: +(ct + d).toFixed(1) }; ct += d; return cue; });
    const seg = { id: s.id, estStart: +t.toFixed(1), estEnd: +(t + segDur).toFixed(1), cues: out };
    t += segDur;
    return seg;
  });
  return { narration, captions, spoken, est, cueSegments, canonical: canonicalUrl(post) };
}

/** Hash of what is said and shown; any change re-opens review and production. */
export function scriptHash(script) {
  const core = script.segments.map((s) => ({ id: s.id, spoken: s.spoken, caption: s.caption ?? null, screen: s.screen ?? [], niqqudOverrides: s.niqqudOverrides ?? null }));
  return sha256(JSON.stringify(core));
}

/** Hash of the source blocks the script cites; a change means the script must be re-checked. */
export function refsHash(script, post) {
  const blocks = new Map(sourceBlocks(post).map((b) => [b.id, b]));
  const ids = [...new Set(script.segments.flatMap((s) => s.refs || []))].sort();
  return sha256(ids.map((id) => `${id}:${blocks.get(id)?.hash ?? 'missing'}`).join('\n'));
}

/**
 * All checks for one package. Errors block production; warnings are reported.
 * None of these checks claims the niqqud or the pronunciation is right: they check
 * consistency, letters and characters. Listening to the chosen voice is the only proof.
 */
export function checkPackage(pkg, post, glossary, { recorded } = {}) {
  const errors = [];
  const warnings = [];
  const script = readScript(pkg.scriptPath);
  const where = (s, m) => `${pkg.postId}/${pkg.variant}#${s}: ${m}`;
  if (script.postId !== pkg.postId || script.variant !== pkg.variant) errors.push(where('-', 'postId/variant in script.json do not match its folder'));
  const blocks = new Map(sourceBlocks(post).map((b) => [b.id, b]));
  const ids = new Set();
  const r = render(script, post, glossary);

  script.segments.forEach((s, i) => {
    if (ids.has(s.id)) errors.push(where(s.id, 'duplicate segment id'));
    ids.add(s.id);
    for (const ref of s.refs || []) if (!blocks.has(ref)) errors.push(where(s.id, `source ref ${ref} does not exist in the post`));
    if (s.role !== 'cta' && !(s.refs || []).length) errors.push(where(s.id, 'segment has no source reference'));
    for (const p of spokenTextProblems(r.narration[i])) errors.push(where(s.id, `narration: ${p}`));
    if (stripNiqqud(r.narration[i]) !== s.spoken.normalize('NFC')) errors.push(where(s.id, 'stripping niqqud from the narration does not give back the spoken text'));
    // Every pointed word must come from the glossary (or a documented per-segment override).
    for (const tok of words(r.narration[i])) {
      if (!/[\u05B0-\u05BC\u05C1\u05C2\u05C7]/.test(tok)) continue;
      const bare = stripNiqqud(tok).replace(/[^א-ת]/g, '');
      const ok = s.niqqudOverrides?.[bare] || glossary.byToken.get(bare);
      if (!ok) errors.push(where(s.id, `pointed word "${tok}" has no glossary entry`));
    }
    // A glossary term that appears with a different prefix must be listed too, or the
    // same word is pointed in one place and left to the engine in another.
    for (const tok of words(r.narration[i])) {
      if (/[\u05B0-\u05BC\u05C1\u05C2\u05C7]/.test(tok)) continue;
      const bare = tok.replace(/[^\u05D0-\u05EA]/g, '');
      const fam = glossary.families.get(stem(bare));
      if (fam && !glossary.byToken.has(bare) && !glossary.unpointedOkSet.has(bare)) (fam.priority ? errors : warnings).push(where(s.id, `"${bare}" is a form of glossary term(s) ${fam.tokens.join(', ')} but has no entry`));
    }
    for (const [k] of Object.entries(s.niqqudOverrides || {})) {
      if (stripNiqqud(s.niqqudOverrides[k]) !== k) errors.push(where(s.id, `override for ${k} changes letters`));
      if (!s.niqqudReason?.[k]) errors.push(where(s.id, `override for ${k} has no niqqudReason`));
    }
    const cap = r.captions[i];
    if (/[\u0591-\u05BD\u05BF\u05C1\u05C2\u05C4\u05C5\u05C7]/.test(cap)) errors.push(where(s.id, 'caption contains niqqud'));
    if (cap !== cap.normalize('NFC')) errors.push(where(s.id, 'caption not NFC'));
    for (const p of unisolatedMath(cap)) errors.push(where(s.id, `caption: ${p}`));
    if (/[{}]/.test(cap)) errors.push(where(s.id, 'caption: unbalanced {{ }}'));
    if (s.caption !== undefined && removeIsolates(cap) !== s.spoken) {
      if (!CAPTION_DIFF_REASONS[s.captionDiff]) errors.push(where(s.id, 'caption differs from the spoken text without a documented captionDiff reason'));
    }
    if (s.caption === undefined && s.captionDiff) warnings.push(where(s.id, 'captionDiff set but caption equals spoken text'));
    // Every formula on screen or in the caption is checked exactly.
    // A screen item may show a false statement on purpose (the mistake being taught) with
    // "expect": "false"; the checker then requires it to be false.
    const falseShown = (s.screen || []).filter((x) => x.kind === 'formula' && x.expect === 'false');
    for (const x of falseShown) {
      const res = checkFormula(x.text.replace(/\?/g, '').trim());
      if (res.status !== 'wrong') errors.push(where(s.id, `formula "${x.text}" is marked as a shown mistake but is not false (${res.status})`));
    }
    const formulas = [...(s.screen || []).filter((x) => x.kind === 'formula' && x.expect !== 'false').map((x) => x.text), ...[...cap.matchAll(new RegExp(`${LRI}([^${PDI}]*)${PDI}`, 'g'))].map((m) => m[1])];
    for (const f of formulas) {
      if (!/[\d]/.test(f)) continue;
      const res = checkFormula(f.replace(/\?/g, '').trim());
      if (res.status === 'wrong' || res.status === 'error') errors.push(where(s.id, `formula "${f}": ${res.status} — ${res.detail}`));
      if (res.status === 'symbolic') warnings.push(where(s.id, `formula "${f}" is symbolic; checked by hand only`));
    }
    for (const m of s.math || []) {
      if (!s.spoken.includes(m.spoken)) errors.push(where(s.id, `math pair: "${m.spoken}" is not in the spoken text`));
      if (!formulas.some((f) => f.replace(/\s/g, '').includes(m.display.replace(/\s/g, '')))) errors.push(where(s.id, `math pair: "${m.display}" is not shown on screen or in the caption`));
      if (m.manual) { warnings.push(where(s.id, `math pair "${m.display}" checked by hand: ${m.manual}`)); continue; }
      let res;
      try { res = compareSpokenToDisplay(m.spoken, m.display); } catch (e) { res = { ok: false, detail: e.message }; }
      if (!res.ok) errors.push(where(s.id, `spoken math does not match the display: ${res.detail}`));
    }
  });

  const { minSec, maxSec } = script.target || {};
  const est = r.est;
  if (est.mid < minSec * 0.9 || est.mid > maxSec * 1.1) errors.push(where('-', `estimated ${est.mid}s is outside ${minSec}–${maxSec}s by more than 10%`));
  else if (est.mid < minSec || est.mid > maxSec) warnings.push(where('-', `estimated ${est.mid}s is just outside ${minSec}–${maxSec}s`));

  const cur = { sourceHash: sourceHash(post), refsHash: refsHash(script, post), scriptHash: scriptHash(script) };
  // reviewedAgainst is stamped (bin/stamp.mjs) after a script is reviewed against its post.
  // A later change to the post, or to the script, re-opens the review.
  const rev = script.reviewedAgainst;
  let review = 'not-reviewed';
  if (rev) {
    if (rev.scriptHash !== cur.scriptHash) review = 'script-changed-since-review';
    else if (rev.refsHash !== cur.refsHash) review = 'cited-source-changed';
    else if (rev.sourceHash !== cur.sourceHash) review = 'post-changed-elsewhere';
    else review = 'current';
  }
  if (review !== 'current') warnings.push(where('-', `review status: ${review}`));
  return { errors, warnings, render: r, hashes: cur, script, review };
}
