const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const path=require('path');const {JSDOM,VirtualConsole}=require('jsdom');
function boot(){const errors=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const dom=new JSDOM(fs.readFileSync(path.join(__dirname,'index.html'),'utf8'),{runScripts:'dangerously',url:'https://example.test/tools/fx-82ms/',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){w.CSS={escape:s=>s};}});const d=dom.window.document;return {dom,d,errors,press(...keys){keys.forEach(key=>{const b=d.querySelector(`[data-key="${key}"]`);assert.ok(b,key);b.click();});},get result(){return d.querySelector('#ms-lcd').dataset.result;},get expression(){return d.querySelector('#ms-lcd').dataset.expression;}};}
test('actual built page: all 50 physical keys, no missing listeners/runtime errors',()=>{const c=boot();try{assert.equal(c.d.querySelectorAll('[data-key]').length,50);assert.equal(c.result,'0.');for(const b of c.d.querySelectorAll('[data-key]')){c.press('on');b.click();}assert.deepEqual(c.errors,[]);}finally{c.dom.window.close();}});
test('built UI fractions, editing, SHIFT display, and segmented result',()=>{const c=boot();try{c.press('2','fraction','3','+','1','fraction','5','equals');assert.equal(c.result,'13┘15');assert.ok(c.d.querySelectorAll('#ms-lcd polygon').length>8);c.press('fraction');assert.equal(c.result,'0.8666666667');c.press('shift');assert.equal(c.d.querySelector('[data-key="shift"]').getAttribute('aria-pressed'),'true');c.press('ac');assert.equal(c.result,'');c.press('on');assert.equal(c.result,'0.');assert.deepEqual(c.errors,[]);}finally{c.dom.window.close();}});
test('built UI keyboard edits and calculator keys share input',()=>{const c=boot();try{for(const key of ['4','*','3','+','2','Enter','ArrowLeft','Backspace','Backspace','-','7','Enter'])c.d.dispatchEvent(new c.dom.window.KeyboardEvent('keydown',{key,bubbles:true,cancelable:true}));assert.equal(c.result,'5.');c.press('ac','sin','6','0','+','cos','9','0','equals');assert.equal(c.result,'0.8660254038');assert.match(c.d.querySelector('#ms-readable').textContent,/0.8660254038/);assert.deepEqual(c.errors,[]);}finally{c.dom.window.close();}});
test('built UI regression selection and statistics',()=>{const c=boot();try{c.press('mode','2','5','memory','7','memory','ac','shift','2','1','equals');assert.equal(c.result,'6.');assert.equal(c.d.querySelector('.ms-device').dataset.mode,'SD');c.press('mode','3','right','3');assert.equal(c.d.querySelector('.ms-device').dataset.mode,'REG');assert.deepEqual(c.errors,[]);}finally{c.dom.window.close();}});
test('built UI legends agree with model-specific keys',()=>{const c=boot();try{assert.match(c.d.querySelector('.key-1 .shift-legend').textContent,/S-SUM/);assert.match(c.d.querySelector('.key-2 .shift-legend').textContent,/S-VAR/);assert.equal(c.d.querySelector('.key-fraction button').textContent,'a b/c');assert.equal(c.d.querySelector('.key-pol .shift-legend').textContent,'Rec(');assert.equal(c.d.querySelector('.key-comma .alpha-legend').textContent,'Y');assert.ok(!c.d.querySelector('[data-key="integral"]'));}finally{c.dom.window.close();}});
test('selector keeps the ES document unchanged and mounts MS lazily',()=>{
 const dom=new JSDOM(fs.readFileSync(path.join(__dirname,'calculators.html'),'utf8'),{runScripts:'dangerously',url:'https://example.test/tools/scientific-calculator/calculators.html',pretendToBeVisual:true});try{const d=dom.window.document,es=d.querySelector('#panel-es991 iframe'),ms=d.querySelector('#panel-ms82 iframe');assert.equal(ms.getAttribute('src'),null);assert.equal(d.querySelector('#panel-ms82').hidden,true);d.querySelector('#tab-ms82').click();assert.match(ms.src,/fx-82ms/);assert.equal(d.querySelector('#panel-es991').hidden,true);assert.equal(d.querySelector('#tab-ms82').getAttribute('aria-selected'),'true');d.querySelector('#tab-es991').click();assert.equal(d.querySelector('#panel-es991 iframe'),es);assert.equal(d.querySelector('#panel-ms82 iframe'),ms);assert.equal(d.querySelector('#panel-es991').hidden,false);d.querySelector('#tab-es991').dispatchEvent(new dom.window.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));assert.equal(d.activeElement.id,'tab-ms82');}finally{dom.window.close();}
});
