const fs=require('fs');const path=require('path');
const esc=s=>s.replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;');
const science=[
 ['inverse','x<sup>−1</sup>','x!','','הופכי'],['ncr','nCr','nPr','','צירופים'],null,null,['pol','Pol(','Rec(',':','קואורדינטות קוטביות'],['cube','x<sup>3</sup>','³√','','חזקה שלישית'],
 ['fraction','a b/c','d/c','','שבר'],['sqrt','√','','','שורש ריבועי'],['square','x<sup>2</sup>','','','ריבוע'],['power','^','<sup>x</sup>√','','חזקה'],['log','log','10<sup>x</sup>','','לוגריתם'],['ln','ln','e<sup>x</sup>','e','לוגריתם טבעי'],
 ['negative','(−)','','A','סימן שלילי'],['dms','° ′ ″','←','B','מעלות דקות שניות'],['hyp','hyp','','C','פונקציות היפרבוליות'],['sin','sin','sin<sup>−1</sup>','D','סינוס'],['cos','cos','cos<sup>−1</sup>','E','קוסינוס'],['tan','tan','tan<sup>−1</sup>','F','טנגנס'],
 ['rcl','RCL','STO','','זיכרון'],['eng','ENG','←','','כתיב הנדסי'],['open','(','','','סוגר פותח'],['close',')','','X','סוגר סוגר'],['comma',',',';','Y','פסיק'],['memory','M+','M−','M','הוספה לזיכרון או נתון סטטיסטי']
];
const numeric=[['7','7'],['8','8'],['9','9'],['del','DEL','INS'],['ac','AC','OFF'],['4','4'],['5','5'],['6','6'],['mul','×'],['div','÷'],['1','1','S-SUM'],['2','2','S-VAR'],['3','3'],['+','+'],['-','−'],['0','0','Rnd'],['dot','.','Ran#'],['exp','×10<sup>x</sup>','π'],['ans','Ans','DRG▶'],['equals','=','%']];
function key(d,kind='science'){if(!d)return '<div class="key-space" aria-hidden="true"></div>';const[id,main,shift='',alpha='',help='']=d;return `<div class="key-slot ${kind} key-${id}"><div class="legends" aria-hidden="true"><span class="shift-legend">${shift}</span><span class="alpha-legend">${alpha}</span></div><button type="button" data-key="${id}" aria-label="${esc(id==='equals'?'= — שווה':id.match(/^\d$/)?id:main.replace(/<[^>]+>/g,'')+(help?' — '+help:''))}" title="${esc([main.replace(/<[^>]+>/g,''),help,shift?'SHIFT: '+shift.replace(/<[^>]+>/g,''):'',alpha?'ALPHA: '+alpha:''].filter(Boolean).join(' · '))}">${main}</button>${id==='memory'?'<span class="dt-legend" aria-hidden="true">DT <span>CL</span></span>':''}</div>`;}
const controls=[['shift','SHIFT','shift'],['alpha','ALPHA','alpha'],['mode','MODE <span>CLR</span>','mode'],['on','ON','on']].map(([id,label,cl])=>`<div class="control ${cl}"><span aria-hidden="true">${label}</span><button type="button" data-key="${id}" aria-label="${id.toUpperCase()}"></button></div>`).join('');
const html=`<main class="ms-page"><div class="ms-stage"><section class="ms-device" aria-label="מחשבון fx-82MS מהדורה שנייה" dir="ltr"><div class="case-face"></div><div class="brand" aria-hidden="true">CASIO</div><div class="model" aria-hidden="true">fx-82MS</div><div class="sv-pam" aria-hidden="true">S-V.P.A.M.</div><div class="edition" aria-hidden="true">2nd edition</div><div class="screen-frame"><div class="screen"><svg id="ms-lcd" viewBox="0 0 360 112" aria-hidden="true"></svg><output id="ms-readable" class="sr-only" aria-live="polite" aria-atomic="true"></output></div></div><div class="controls">${controls}<div class="replay" aria-label="חצי ניווט"><div class="replay-ring"></div>${['up','left','right','down'].map((d,i)=>`<button type="button" class="arrow ${d}" data-key="${d}" aria-label="${['למעלה','שמאלה','ימינה','למטה'][i]}"><span></span></button>`).join('')}</div></div><div class="science-pad">${science.map(d=>key(d)).join('')}</div><div class="numeric-pad">${numeric.map(d=>key(d,'number')).join('')}</div></section></div><details class="ms-help"><summary>איך משתמשים בדגם הזה?</summary><div><p><strong>שבר:</strong> לחצו <bdi>2 → a b/c → 3</bdi> כדי להזין שני שלישים. השבר מופיע בשורה אחת. אחרי <bdi>=</bdi>, המקש <bdi>a b/c</bdi> מחליף בין שבר לעשרוני.</p><p><strong>פעולה צהובה:</strong> לחצו <bdi>SHIFT</bdi> ואחריו על המקש. אות אדומה: <bdi>ALPHA</bdi> ואז המקש.</p><p><strong>מצבים:</strong> <bdi>MODE → 1</bdi> לחישוב רגיל, <bdi>2</bdi> לסטטיסטיקה, <bdi>3</bdi> לרגרסיה. לחיצות נוספות על <bdi>MODE</bdi> מציגות יחידות זווית ואפשרויות תצוגה.</p><p><strong>תיקון תרגיל:</strong> החצים מזיזים את הסמן. הקלדה מחליפה את התו שעליו הסמן; <bdi>SHIFT → DEL</bdi> מעביר למצב הוספה.</p><p>אפשר להשתמש גם בספרות, בפעולות ובחצים של המקלדת. <bdi>Enter</bdi> מחשב ו־<bdi>Esc</bdi> מנקה.</p><p class="note">כלי תרגול עצמאי לפי הדגם. אינו מוצר רשמי של CASIO; ייתכנו הבדלים בקירוב מספרי ובמקרי קצה.</p><a href="https://support.casio.com/global/en/calc/manual/fx-82MS_85MS_220PLUS_300MS_350MS_en/" target="_blank" rel="noopener noreferrer">מדריך הדגם באתר CASIO ↗</a></div></details></main>`;
fs.writeFileSync(path.join(__dirname,'ui.html'),html);
