'use strict';
const fs=require('fs'),path=require('path');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const keys=[
 ['calc','CALC','SOLVE','=', 'top-left'],['integral','∫<span class="tiny">▢</span>','d/dx','∶','top-second'],['inverse','x⁻¹','x!','','top-fifth'],['logbase','log<sub>▢</sub>▢','Σ','','top-last'],
 ['fraction','<span class="fraction-icon"><i>▰</i><i>▰</i></span>','<span class="mixed-icon">▯ ▰/▰</span>',''],['sqrt','√<span class="tiny">▢</span>','³√',''],['square','x²','x³','','','DEC'],['power','x<span class="power-small">▢</span>','<sup>▢</sup>√','','','HEX'],['log','log','10ˣ','','','BIN'],['ln','ln','eˣ','','','OCT'],
 ['negative','(−)','∠','A'],['dms','°′″','←','B'],['hyp','hyp','Abs','C'],['sin','sin','sin⁻¹','D'],['cos','cos','cos⁻¹','E'],['tan','tan','tan⁻¹','F'],
 ['rcl','RCL','STO',''],['eng','ENG','←','','','i'],['lparen','(','%',''],['rparen',')',',','X'],['sd','S⇔D','a<span class="tiny">b/c</span>⇔<span class="tiny">d/c</span>','Y'],['mplus','M+','M−','M']
];
const numbers=[['7','7','CONST'],['8','8','CONV'],['9','9','CLR'],['del','DEL','INS','','clear'],['ac','AC','OFF','','clear'],['4','4','MATRIX'],['5','5','VECTOR'],['6','6',''],['mul','×','nPr'],['div','÷','nCr'],['1','1','STAT'],['2','2','CMPLX'],['3','3','BASE-N'],['add','+','Pol'],['sub','−','Rec'],['0','0','Rnd'],['dot','.','Ran#','RanInt'],['exp','×10ˣ','π','e'],['ans','Ans','DRG▶'],['equals','=','']];
const names={integral:'אינטגרל',inverse:'הופכי',logbase:'לוגריתם בבסיס משתנה',fraction:'שבר',sqrt:'שורש',square:'ריבוע',power:'חזקה',negative:'סימן שלילי',dms:'מעלות דקות שניות',rcl:'שליפה מזיכרון',sd:'שבר או עשרוני S D',mplus:'הוספה לזיכרון M',del:'DEL מחיקה',ac:'AC ניקוי',exp:'כפול עשר בחזקה',equals:'שווה',mul:'כפל',div:'חילוק',add:'חיבור',sub:'חיסור',dot:'נקודה עשרונית'};
function key([id,label,shift='',alpha='',extra='',base='']){return `<button type="button" class="device-key ${extra}" data-key="${id}" data-shift="${esc(shift.replace(/<[^>]*>/g,''))}" aria-label="${esc(names[id]||label.replace(/<[^>]*>/g,''))}" title="${esc((names[id]||label.replace(/<[^>]*>/g,''))+(shift?' · SHIFT: '+shift.replace(/<[^>]*>/g,''):'')+(alpha?' · ALPHA: '+alpha:''))}"><span class="key-legend" aria-hidden="true"><span class="shift-legend">${shift}</span><span class="alpha-legend">${alpha}</span>${base?'<span class="base-legend">'+base+'</span>':''}</span><span class="keycap" aria-hidden="true">${label}</span></button>`;}
const html=`<style>${fs.readFileSync(path.join(__dirname,'device.css'),'utf8')}</style>
<main class="calculator-page" aria-label="מחשבון מדעי">
<div class="device-stage"><section id="casio-calc" class="device-shell" dir="ltr" aria-label="סימולטור לימודי fx-991ES PLUS">
 <header class="device-brand"><div class="brand-name">CASIO</div><div class="solar-panel" aria-hidden="true"></div><div class="model-name">fx-991ES PLUS</div><div class="natural-brand">NATURAL-V.P.A.M.</div><div class="edition">2nd edition</div></header>
 <div class="lcd-bezel"><div class="lcd" aria-label="מסך המחשבון"><div id="lcd-status" aria-live="off">D <span>Math</span></div><input id="lcd-input" type="text" inputmode="none" autocomplete="off" autocapitalize="off" spellcheck="false" aria-label="ביטוי לחישוב" dir="ltr"><div id="lcd-expression" aria-label="ביטוי מתמטי"></div><div id="lcd-result" aria-label="תוצאה">0</div><div id="lcd-menu" hidden></div></div></div>
 <div class="control-row"><div class="control-pair"><button type="button" class="round-control shift-control" data-key="shift" aria-label="SHIFT" aria-pressed="false"><span>SHIFT</span><i></i></button><button type="button" class="round-control alpha-control" data-key="alpha" aria-label="ALPHA" aria-pressed="false"><span>ALPHA</span><i></i></button></div><div class="replay-pad" role="group" aria-label="REPLAY חיצי עריכה"><button data-key="up" aria-label="למעלה והיסטוריה" class="arrow up">▲</button><button data-key="left" aria-label="שמאלה" class="arrow left">◀</button><div class="replay-center" aria-hidden="true"></div><button data-key="right" aria-label="ימינה" class="arrow right">▶</button><button data-key="down" aria-label="למטה והיסטוריה" class="arrow down">▼</button></div><div class="control-pair"><button type="button" class="round-control mode-control" data-key="mode" aria-label="MODE SETUP"><span>MODE <b>SETUP</b></span><i></i></button><button type="button" class="round-control" data-key="on" aria-label="ON הפעלה"><span>ON</span><i></i></button></div></div>
 <div class="science-keypad" role="group" aria-label="מקשי מדע וזיכרון">${keys.map(key).join('')}</div>
 <div class="number-keypad" role="group" aria-label="מקשי ספרות וחשבון">${numbers.map(key).join('')}</div>
</section></div>
<p class="device-caption" dir="rtl">סימולטור לימודי לפי fx‑991ES PLUS · נועם דורון</p>
<details class="device-help" dir="rtl"><summary>עזרה בהפעלה</summary><p>לחצו על המקשים כמו במחשבון: SHIFT לפעולות הצהובות, ALPHA לסימונים האדומים, MODE לבחירת מצב ו־SHIFT ואז MODE להגדרות. אפשר גם להקליד מהמקלדת ולחשב עם Enter.</p><p>זהו סימולטור לימודי עצמאי בדפדפן. החיצים מזיזים את הסמן בתוך הביטוי ומחזירים חישובים קודמים. S⇔D מחליף בין תצוגה מדויקת לעשרונית.</p><p><a href="https://support.casio.com/global/en/calc/manual/fx-570ESPLUS_991ESPLUS_en/" target="_blank" rel="noopener">מדריך ההפעלה של הדגם</a></p></details>
<div id="calc-announcer" class="visually-hidden" role="status" aria-live="polite" aria-atomic="true"></div>
</main>`;
fs.writeFileSync(path.join(__dirname,'ui.html'),html);
console.log('Physical keypad: '+(keys.length+numbers.length+8)+' keys');
